repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [
          "flake8-bandit",
          "flake8-black",
          "flake8-blind-except",
          "flake8-broken-line",
          "flake8-bugbear",
          "flake8-builtins",
          "flake8-comprehensions",
          "flake8-eradicate",
          "flake8-isort",
          "flake8-logging-format",
          "flake8-pytest-style",
          "flake8-use-fstring",
        ]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        pass_filenames: false
        language: system
        entry: poetry run mypy .
