[tool.poetry]
name = "catchall-api"
version = "1.0.0"
description = "Catchall API that echoes back requests"
authors = ["Mathieu Lemay <acidrain1@gmail.com>"]
license = "MIT"
readme = "README.md"
include = ["catchall_api/py.typed"]

[tool.poetry.scripts]
catchall-api = 'catchall_api.api:main'

[tool.poetry.dependencies]
python = "^3.10"
pydantic = {version = "^1.10.2", extras = ["dotenv"]}
fastapi = "^0.85.0"
requests = "^2.28.1"
coloredlogs = "^15.0.1"
uvicorn = "^0.19.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
pytest-asyncio = "^0.19.0"
mypy = "^0.982"
httpx = "^0.23.0"
pytest-docker = "^1.0.1"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.mypy]
namespace_packages=true
explicit_package_bases=true
strict=true
show_error_codes=true

[tool.pytest.ini_options]
minversion = "6.0"
# Disable anyio to avoid conflict and force asyncio to load before entrypoints
# https://docs.pytest.org/en/6.2.x/writing_plugins.html#plugin-discovery-order-at-tool-startup
# Also force pytest_alembic to load before boostsec_database for fixture overrides
addopts = ["-p", "no:anyio", "-p", "asyncio"]
testpaths = ["tests"]
asyncio_mode = "auto"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
