---
name: Run tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Setup poetry cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install Dependencies
        run: |
          just install

      - name: Lint
        uses: pre-commit/action@v3.0.0

      - name: Run tests
        run: |
          just test
